services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_DATABASE: 'tasks_app'
      MYSQL_USER: 'damian'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - my-db:/var/lib/mysql

  spring-app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  my-db: